### ISSUE TITLE
About Main.js Error

### ISSUE THREAD

**Issue by annak1n** [henrytriplette/hexa-2.0#3]
Hi i try to run u project and i get this error:

`Error: Cannot find module '/root/hexa/main.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)`

Can u help me ?

**Comment by henrytriplette** [comment]
Hi, sorry, haven't run this project in months.

As far as I remember, "client"  folder of the project is deprecated, now the "server" runs both the communication part and the frontend.

So discard the client, just run the server.py and it should spin up a Flask instance on localhost
